# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'LGlassesKit_iOS_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LGlassesKit_iOS_Demo

  pod 'Masonry'
  pod 'Realm'
  pod 'SVProgressHUD'
  pod 'libopus'
  
  # 眼镜
  pod 'LGlassesKit_iOS', git: 'https://github.com/wsr1949/LGlassesKit_iOS.git'
  # AI
  pod 'iOS_LWAIGCKit', git: 'https://github.com/wsr1949/iOS_LWAIGCKit.git'

end
